import { GoogleSpreadsheet } from 'google-spreadsheet';
import { JWT } from 'google-auth-library';
import credential from './high-essence-410306-10047835f6dd.json';

if (typeof window === 'undefined') {
  // Node.js 서버 사이드에서만 실행되는 코드
  const fs = require('fs');
  // 나머지 코드
}

const serviceAccountAuth = new JWT({
  // env var values here are copied from service account credentials generated by google
  // see "Authentication" section in docs for more info
  email: credential.client_email,
  key: credential.private_key,
  scopes: ['https://www.googleapis.com/auth/spreadsheets'],
});

// 구글 시트 조회하는 로직
export const getGoogleSheet: () => Promise<GoogleSpreadsheet> = async () => {
  const doc = new GoogleSpreadsheet('1f9EzH7k9_7Icp-FQOjaNW5yLH_6woN4VWUV_03Tljf8', serviceAccountAuth);
  // 구글 인증이 필요하다.
  //await doc.useServiceAccountAuth(credential);
  await doc.loadInfo();
  return doc;
};
